import "metro4/source/core.js"
import "metro4/source/common/common-css"
import "metro4/source/colors"
import "metro4/source/components/colors"
import "metro4/source/components/accordion"
import "metro4/source/icons"